### ISSUE TITLE
Issue building on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by neozeed** [quozl/pptpd#1]
So Ubuntu decided to remove the pptpd package kind of leaving me in the wind.

I did install the ppp-dev	package giving me some of the heades but I can't figure out where the pppd/optiosn should be?

<pppd/options.h>

Maybe it got removed in Linux v6?

Linux ukweb 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by quozl** [comment]
Ubuntu 24.04 LTS has an older 2.4.x release of ppp, which doesn't have that file.  Revert the commit b77d92c025992b246083142587f3c3b5f115832d to build with that release.

Or upgrade to later ppp, see https://github.com/ppp-project/ppp

**Comment by neozeed** [comment]
ill give it a shot tonight! thanks for the tip!

**Comment by quozl** [comment]
how did that go?

**Comment by neozeed** [comment]
sorry I had some irl stuff pop up.  I'm still missing pppd.h ... I think its the kernel that I'm forced to use:

`
gcc -o pptpd-logwtmp.so -shared -O2 -g -I.. -I../../include -fPIC pptpd-logwtmp.c -lutil
pptpd-logwtmp.c:17:10: fatal error: pppd/pppd.h: No such file or directory
   17 | #include <pppd/pppd.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
`

Linux v19857 6.1.0-21-cloud-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

I took binaries from another system and it fails as there is no ppp modules.  Looks like this 'cloud' version of Debian decided ppp shouldn't be around anymore.

`
/var/log/syslog.1:2024-06-15T10:43:30.692556+00:00 v19857 pptpd[8236]: CTRL: Starting call (launching pppd, opening GRE)
/var/log/syslog.1:2024-06-15T10:43:30.706439+00:00 v19857 pppd[8237]: Plugin /usr/lib/pptpd/pptpd-logwtmp.so loaded.
/var/log/syslog.1:2024-06-15T10:43:30.714436+00:00 v19857 pppd[8237]: Couldn't open the /dev/ppp device: No such device or address
/var/log/syslog.1:2024-06-15T10:43:30.714656+00:00 v19857 pppd[8237]: Please load the ppp_generic kernel module.
/var/log/syslog.1:2024-06-15T10:43:30.714788+00:00 v19857 pptpd[8237]: /usr/sbin/pppd: Please load the ppp_generic kernel module.
/var/log/syslog.1:2024-06-15T10:43:30.715005+00:00 v19857 pptpd[8236]: GRE: read(fd=6,buffer=564a88e98520,len=8196) from PTY failed: status = -1 error = Input/output error, usually caused by unexpected termination of pppd, check option syntax and pppd logs
`

and

`
root@v19857:/usr/lib/modules/6.1.0-21-cloud-amd64# find ./ -name '*ppp*'
root@v19857:/usr/lib/modules/6.1.0-21-cloud-amd64#
`

I guess I'll have to UML or KVM something with a more complete kernel.

**Comment by quozl** [comment]
Thanks.

Yes, the Debian cloud kernels (linux-image-cloud-amd64 and dependencies) don't have the ppp modules.  You could rebuild the kernels with a changed configuration, but that means you have to keep doing that on each security update. 

I've looked into the linux-image-6.1.0-21-amd64_6.1.90-1_amd64.deb package and the ppp modules are present.  But still, if you're forced, there is probably some underlying reason and you'll have to negotiate with your captors.

**Comment by neozeed** [comment]
I should have guessed with the fundamental reason it wouldn't compile.  Thanks anyway!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by quozl** [comment]
Oh, sorry, I missed that, compile should have worked.  Compile doesn't need kernel support.  It just won't run without kernel support.

> pppd/pppd.h: No such file or directory

This file is placed by the `ppp-dev` package.

(In your opening comment you were using 6.8.0-35-generic, therefore Ubuntu 24.04, which has ppp 2.4.9, which requires reverting b77d92c025992b246083142587f3c3b5f115832d to build.  I've just tested this again.  I see you've then gone on to compile on the Debian kernel 6.1.0-21-cloud-amd64 but my guess is that you didn't have `ppp-dev` installed, or _actually_ you're building with a later version of ppp than Ubuntu 24.04.  No matter, as you need the ppp kernel modules to run.)

**Comment by neozeed** [comment]
beats me!

`
root@v19857:~/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d# apt-get install ppp-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ppp-dev is already the newest version (2.4.9-1+1.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@v19857:~/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d# make
make  all-am
make[1]: Entering directory '/root/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d'
for d in plugins; do make -w -C $d all; done
make[2]: Entering directory '/root/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d/plugins'
gcc -o pptpd-logwtmp.so -shared -O2 -g -I.. -I../../include -fPIC pptpd-logwtmp.c -lutil
pptpd-logwtmp.c:18:10: fatal error: pppd/options.h: No such file or directory
   18 | #include <pppd/options.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:19: pptpd-logwtmp.so] Error 1
make[2]: Leaving directory '/root/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d/plugins'
make[1]: *** [Makefile:840: all-local] Error 2
make[1]: Leaving directory '/root/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d'
make: *** [Makefile:277: all] Error 2
root@v19857:~/src/pptpd-b77d92c025992b246083142587f3c3b5f115832d#
`

**Comment by quozl** [comment]
Okay, ppp-dev 2.4.9 does not provide options.h, so _revert_ the commit https://github.com/quozl/pptpd/commit/b77d92c025992b246083142587f3c3b5f115832d to build with that release.  Perhaps you checked out that commit instead.  If you'd like to build from a checkout rather than reverting, 3b7a80c3b63a9f9388991299f76c245bb900875e is the commit before b77d92c025992b246083142587f3c3b5f115832d.
